### ISSUE TITLE
Project won't start

### ISSUE THREAD

**Issue by udmteh** [willsanchez86/nft-minting-dapp#1]
Project won't start
After installation, http://localhost:3000/ is just a white page. there are no errors.

**Comment by willsanchez86** [comment]
Thanks for bringing this to my attention. 

I've found that the issue occurs due to missing environment variables, which are included on my gitignore and not uploaded to this repo. 

Please follow the following instructions on creating a .env file of your own in the root of your this project, then fill out using the exact variable names listed below: 

      REACT_APP_NEXT_PUBLIC_ALCHEMY_RPC_URL=<Your Public Alchemy Rpc URL>
          # 1. Visit https://dashboard.alchemyapi.io/signup/chain and create an account
          # 2. Select Ethereum as your Ecosysten and hit "Get Started"
          # 3. Fill out Form Fields, choose Rinkeby as network, and click "Create App"
          # 4. Choose your preferred plan (Free Recommended)
          # 5. Skip for now on the Payment Info Page
          # 6. Choose "Capped Capacity" Scaling Policy then hit Continue
          # 7. Copy and paste the https:... link as the value for this environment variable

      REACT_APP_NEXT_PUBLIC_FORTMATIC_KEY=<Your Public Fortmatic API Key>
          # Visit https://dashboard.fortmatic.com/login and create an account. Copy & Paste the test API Key as the value for this environment variable -->

      REACT_APP_METAMASK_PRIVATE_KEY=<Your Metamask Private Key>
          # Copy & Paste your Metamask Private Key (WARNING: DO NOT SHARE THESE KEYS WITH ANYONE AND BE VERY CAREFUL NOT TO EXPOSE THESE ONLINE!!)

      REACT_APP_METAMASK_DEFAULT_ACCOUNT=<Your Metamask Acct>
          # Copy & Paste your Metamask Account Number 

      REACT_APP_ETHERSCAN_API_KEY=<Your Etherscan API Key>
              # 1. Visit https://etherscan.io/login and create 
              # 2. Copy & Paste your Metamask account an account. 
              # 3. Click on your username and choose "API Key" in the dropdown menu
              # 4. Create a new API Key
              # 5. Copy & Paste it as the value for this environment variable

      REACT_APP_BASE_URI_METADATA=ipfs://QmSGJHJfWFNCHKjU6sfREeFyvE8ywZeoCKoiASL1Qc2Hnp/        # Generic Eye Metadata



The ReadMe has also been updated with these instructions. 

Let me know if this solution still doesn't work for you, and I'll reopen the ticket for further review.
